name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - name: Use Node.js 16.14.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          git config --global user.email "RidhwanDev"
          git config --global user.name "Ridhwan"
          echo "machine github.com login RidhwanDev password $GITHUB_TOKEN" > ~/.netrc
          GIT_USER=RidhwanDev npm run publish-gh-pages
